### ISSUE TITLE
`cannot cast between pointer types: from *f32x2, to *struct ...` in latest versions of `rust-gpu`

### ISSUE THREAD

**Issue by tombh** [Rust-GPU/rust-gpu#160]
### Expected Behaviour
At some point after September 6th ([#4c633aec](https://github.com/Rust-GPU/rust-gpu/commit/4c633aec182300d9f85460ffd5a6ba7904ff5f74)) the following code stopped compiling.

```rust
pub struct Particles {
    pub indices: Indices,
    pub data: [Particle; MAX_PARTICLES_IN_CELL * REQUIRED_CELLS],
    pub centre_count: usize,
}

impl Particles {
    pub fn new(
        ...
    ) -> Self {
        let mut particles = Self {
            data: [Particle::default(); MAX_PARTICLES_IN_CELL * REQUIRED_CELLS], // error here
            ...
        };
```

### Example & Steps To Reproduce
I'm compiling with latest `cargo-gpu` (https://github.com/Rust-GPU/cargo-gpu/commit/4623ccb10e90d77f54cb87c6eebebcd96eb6a1f4) and the full error is:

```
error: cannot cast between pointer types
       from `*f32x2`
         to `*struct particle::Particle { position: f32x2, velocity: f32x2, index: u32 }`
   --> shaders/physics/src/particles.rs:56:19
    |
56  |             data: [Particle::default(); MAX_PARTICLES_IN_CELL * REQUIRED_CELLS],
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm happy to bisect to find the exact commit that introduces the change, but just wondering if anybody already knows what the problem is?

**Comment by LegNeato** [comment]
Thanks for the report! This might be https://github.com/Rust-GPU/rust-gpu/issues/46 ?

**Comment by tombh** [comment]
Ah yes, indeed that's it. Thank you ✨
