### ISSUE TITLE
metal support

### ISSUE THREAD

**Issue by sehz** [Rust-GPU/rust-gpu#163]
Hi,  anyone interested in support for Metal?

**Comment by LegNeato** [comment]
We will likely not natively support metal. What you can do is use [naga](https://docs.rs/naga/latest/naga/) with or without `wgpu` to translate the compiled spir-v to metal. Or use MoltenVK.

If someone wanted to make [spir-t](https://github.com/Rust-GPU/spirt) lower to metal, we would entertain it.
