### ISSUE TITLE
Communication channel

### ISSUE THREAD

**Issue by giannissc** [Rust-GPU/rust-gpu#4]
I was just wondering if there plans to use a community platform like discord or zulip for the project?

**Comment by rydb** [comment]
> I was just wondering if there plans to use a community platform like discord or zulip for the project?

I've made a server for it
https://discord.gg/K5Bvw6nx

If maintainers decide to go with something else, I can turn it off and we can switch to whatever that is.

**Comment by LegNeato** [comment]
Please see https://github.com/Rust-GPU/rust-gpu/discussions/5.
